# Generated by Django 3.1.4 on 2021-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210629_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseIMG', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='myuploadfile',
        ),
    ]
